import { Release } from '@/types/releases';

export const mockReleases: Release[] = [
  {
    id: 'REL-001',
    name: 'Summer Update',
    version: '2.0.0',
    type: 'major',
    description: 'Major release with new dashboard, analytics, and performance improvements',
    status: 'in-progress',
    targetDate: '2025-06-30',
    progress: 72,
    healthScore: 78,
    releaseManager: 'user-1',
    teamMembers: ['user-1', 'user-2', 'user-3'],
    stakeholders: ['user-4', 'user-5'],
    features: [
      {
        id: 'rf-001',
        featureId: 'FEAT-001',
        name: 'New Dashboard Interface',
        status: 'done',
        owner: 'user-1',
        storyPoints: 13,
        completionPercent: 100,
        dependencies: [],
      },
      {
        id: 'rf-002',
        featureId: 'FEAT-002',
        name: 'Advanced Analytics',
        status: 'in-testing',
        owner: 'user-2',
        storyPoints: 21,
        completionPercent: 90,
        dependencies: ['rf-001'],
      },
      {
        id: 'rf-003',
        featureId: 'FEAT-003',
        name: 'Performance Optimization',
        status: 'in-development',
        owner: 'user-3',
        storyPoints: 8,
        completionPercent: 65,
        dependencies: [],
      },
      {
        id: 'rf-004',
        featureId: 'FEAT-004',
        name: 'User Preferences',
        status: 'in-development',
        owner: 'user-1',
        storyPoints: 5,
        completionPercent: 40,
        dependencies: ['rf-001'],
      },
    ],
    milestones: [
      {
        id: 'rm-001',
        name: 'Code Freeze',
        targetDate: '2025-06-15',
        criteria: ['All features code complete', 'Code review completed'],
        status: 'pending',
      },
      {
        id: 'rm-002',
        name: 'QA Sign-off',
        targetDate: '2025-06-25',
        criteria: ['Test coverage > 85%', 'All critical bugs fixed'],
        status: 'pending',
      },
    ],
    readinessItems: [
      {
        id: 'ri-001',
        category: 'development',
        title: 'All features code complete',
        completed: true,
        owner: 'user-1',
        dueDate: '2025-06-15',
        notes: 'Completed on schedule',
      },
      {
        id: 'ri-002',
        category: 'testing',
        title: 'Test coverage > 85%',
        completed: false,
        owner: 'user-2',
        dueDate: '2025-06-20',
        notes: 'Currently at 78%, working to increase',
      },
      {
        id: 'ri-003',
        category: 'documentation',
        title: 'Release notes drafted',
        completed: true,
        owner: 'user-4',
        dueDate: '2025-06-20',
        notes: 'Draft ready for review',
      },
    ],
    risks: [
      {
        id: 'rsk-001',
        description: 'Advanced Analytics performance may impact load times',
        severity: 'high',
        mitigationPlan: 'Implement caching and optimize database queries',
        owner: 'user-2',
        status: 'open',
      },
      {
        id: 'rsk-002',
        description: 'User Preferences feature dependencies',
        severity: 'medium',
        mitigationPlan: 'Complete Dashboard first, test integration thoroughly',
        owner: 'user-1',
        status: 'open',
      },
    ],
    deploymentPlan: {
      environments: ['staging', 'production'],
      rolloutStrategy: 'phased',
      rollbackPlan: 'Maintain previous version in production for 48 hours, rollback via database migration if critical issues detected',
    },
    notes: 'Major update with significant UI/UX improvements and backend optimizations',
    createdAt: '2025-04-01T10:00:00Z',
    updatedAt: '2025-05-15T14:30:00Z',
  },
  {
    id: 'REL-002',
    name: 'Bug Fix Release',
    version: '1.9.2',
    type: 'patch',
    description: 'Critical bug fixes and security patches',
    status: 'planning',
    targetDate: '2025-05-20',
    progress: 35,
    healthScore: 85,
    releaseManager: 'user-2',
    teamMembers: ['user-1', 'user-2'],
    stakeholders: ['user-4'],
    features: [
      {
        id: 'rf-005',
        featureId: 'FEAT-005',
        name: 'Security Patch - SQL Injection Fix',
        status: 'in-development',
        owner: 'user-1',
        storyPoints: 5,
        completionPercent: 80,
        dependencies: [],
      },
      {
        id: 'rf-006',
        featureId: 'FEAT-006',
        name: 'Export Function Bug Fix',
        status: 'not-started',
        owner: 'user-2',
        storyPoints: 3,
        completionPercent: 0,
        dependencies: [],
      },
    ],
    milestones: [
      {
        id: 'rm-003',
        name: 'Security Review Complete',
        targetDate: '2025-05-18',
        criteria: ['Security audit passed', 'Vulnerabilities addressed'],
        status: 'pending',
      },
    ],
    readinessItems: [
      {
        id: 'ri-004',
        category: 'development',
        title: 'Code complete',
        completed: true,
        owner: 'user-1',
        dueDate: '2025-05-18',
        notes: '',
      },
    ],
    risks: [],
    deploymentPlan: {
      environments: ['production'],
      rolloutStrategy: 'big-bang',
      rollbackPlan: 'Rollback to 1.9.1 immediately if issues detected',
    },
    notes: 'Critical patch release for security issues',
    createdAt: '2025-05-01T09:00:00Z',
    updatedAt: '2025-05-10T11:00:00Z',
  },
  {
    id: 'REL-003',
    name: 'Spring Features',
    version: '1.9.0',
    type: 'minor',
    description: 'New features and improvements for Q2',
    status: 'complete',
    targetDate: '2025-04-30',
    releaseDate: '2025-04-28',
    progress: 100,
    healthScore: 92,
    releaseManager: 'user-3',
    teamMembers: ['user-1', 'user-2', 'user-3'],
    stakeholders: ['user-4', 'user-5'],
    features: [
      {
        id: 'rf-007',
        featureId: 'FEAT-007',
        name: 'Bulk Import Feature',
        status: 'done',
        owner: 'user-3',
        storyPoints: 8,
        completionPercent: 100,
        dependencies: [],
      },
      {
        id: 'rf-008',
        featureId: 'FEAT-008',
        name: 'Custom Reports',
        status: 'done',
        owner: 'user-2',
        storyPoints: 13,
        completionPercent: 100,
        dependencies: [],
      },
    ],
    milestones: [
      {
        id: 'rm-004',
        name: 'Release to Production',
        targetDate: '2025-04-28',
        criteria: ['All tests passed', 'Performance acceptable'],
        status: 'completed',
      },
    ],
    readinessItems: [
      {
        id: 'ri-005',
        category: 'development',
        title: 'All features code complete',
        completed: true,
        owner: 'user-3',
        dueDate: '2025-04-20',
        notes: 'Completed ahead of schedule',
      },
    ],
    risks: [],
    deploymentPlan: {
      environments: ['staging', 'production'],
      rolloutStrategy: 'big-bang',
      rollbackPlan: 'Standard rollback procedure',
    },
    notes: 'Successfully released with high quality metrics',
    createdAt: '2025-03-01T10:00:00Z',
    updatedAt: '2025-04-28T16:00:00Z',
  },
  {
    id: 'REL-004',
    name: 'Holiday Hotfix',
    version: '1.8.3',
    type: 'hotfix',
    description: 'Critical bug fixes released during holiday period',
    status: 'complete',
    targetDate: '2025-01-02',
    releaseDate: '2025-01-01',
    progress: 100,
    healthScore: 88,
    releaseManager: 'user-1',
    teamMembers: ['user-1'],
    stakeholders: ['user-4'],
    features: [
      {
        id: 'rf-009',
        featureId: 'FEAT-009',
        name: 'Payment Processing Bug Fix',
        status: 'done',
        owner: 'user-1',
        storyPoints: 3,
        completionPercent: 100,
        dependencies: [],
      },
    ],
    milestones: [],
    readinessItems: [],
    risks: [],
    deploymentPlan: {
      environments: ['production'],
      rolloutStrategy: 'big-bang',
      rollbackPlan: 'Immediate rollback if needed',
    },
    notes: 'Emergency hotfix for critical production issue',
    createdAt: '2024-12-31T20:00:00Z',
    updatedAt: '2025-01-01T02:00:00Z',
  },
];
