import { Goal } from '@/types/goals';

export const mockGoals: Goal[] = [
  {
    id: 'GOAL-001',
    type: 'okr',
    title: 'Improve Customer Satisfaction',
    description: 'Increase overall customer satisfaction score and NPS to improve retention and advocacy.',
    objective: 'Customer satisfaction and loyalty',
    owner: 'user-1',
    contributors: ['user-2', 'user-3'],
    status: 'on-track',
    progress: 72,
    keyResults: [
      {
        id: 'kr-001-1',
        title: 'Increase NPS from 45 to 60',
        measurementType: 'number',
        startValue: 45,
        targetValue: 60,
        currentValue: 54,
        owner: 'user-1',
        weight: 40,
        confidenceLevel: 85,
        status: 'on-track',
        lastUpdated: '2025-01-15T10:00:00Z',
        progressHistory: [
          { id: 'ph-1', value: 45, timestamp: '2024-10-01T00:00:00Z', updatedBy: 'user-1', confidenceLevel: 70 },
          { id: 'ph-2', value: 48, timestamp: '2024-11-01T00:00:00Z', updatedBy: 'user-1', confidenceLevel: 75 },
          { id: 'ph-3', value: 52, timestamp: '2024-12-01T00:00:00Z', updatedBy: 'user-1', confidenceLevel: 80 },
          { id: 'ph-4', value: 54, timestamp: '2025-01-15T00:00:00Z', updatedBy: 'user-1', confidenceLevel: 85 },
        ],
      },
      {
        id: 'kr-001-2',
        title: 'Achieve 95% customer retention rate',
        measurementType: 'percentage',
        startValue: 88,
        targetValue: 95,
        currentValue: 91,
        owner: 'user-2',
        weight: 40,
        confidenceLevel: 78,
        status: 'on-track',
        lastUpdated: '2025-01-14T10:00:00Z',
        progressHistory: [
          { id: 'ph-5', value: 88, timestamp: '2024-10-01T00:00:00Z', updatedBy: 'user-2', confidenceLevel: 65 },
          { id: 'ph-6', value: 89, timestamp: '2024-11-01T00:00:00Z', updatedBy: 'user-2', confidenceLevel: 70 },
          { id: 'ph-7', value: 91, timestamp: '2025-01-14T00:00:00Z', updatedBy: 'user-2', confidenceLevel: 78 },
        ],
      },
      {
        id: 'kr-001-3',
        title: 'Complete 50 customer success case studies',
        measurementType: 'number',
        startValue: 0,
        targetValue: 50,
        currentValue: 28,
        owner: 'user-3',
        weight: 20,
        confidenceLevel: 72,
        status: 'on-track',
        lastUpdated: '2025-01-13T10:00:00Z',
        progressHistory: [
          { id: 'ph-8', value: 0, timestamp: '2024-10-01T00:00:00Z', updatedBy: 'user-3', confidenceLevel: 50 },
          { id: 'ph-9', value: 8, timestamp: '2024-11-01T00:00:00Z', updatedBy: 'user-3', confidenceLevel: 60 },
          { id: 'ph-10', value: 18, timestamp: '2024-12-01T00:00:00Z', updatedBy: 'user-3', confidenceLevel: 70 },
          { id: 'ph-11', value: 28, timestamp: '2025-01-13T00:00:00Z', updatedBy: 'user-3', confidenceLevel: 72 },
        ],
      },
    ],
    startDate: '2024-10-01',
    targetDate: '2025-03-31',
    timePeriod: 'Q4 2024 - Q1 2025',
    organization: 'company',
    childGoalIds: ['GOAL-002', 'GOAL-003'],
    updateFrequency: 'weekly',
    autoCalculateFromKPIs: true,
    linkedFeatureIds: ['FEAT-001', 'FEAT-002'],
    linkedSprintIds: ['SPRINT-001', 'SPRINT-002'],
    linkedInitiativeIds: [],
    tags: ['customer', 'satisfaction', 'retention'],
    priority: 'critical',
    visibility: 'public',
    createdAt: '2024-10-01T00:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    updates: [],
    comments: [
      {
        id: 'cmt-1',
        authorId: 'user-1',
        content: 'Great progress on NPS. We should focus on the customer success case studies next.',
        createdAt: '2025-01-15T09:00:00Z',
      },
      {
        id: 'cmt-2',
        authorId: 'user-2',
        content: '@user-1 Agreed! I\'ll prioritize the case study content for next week.',
        createdAt: '2025-01-15T09:30:00Z',
        mentions: ['user-1'],
      },
    ],
  },
  {
    id: 'GOAL-002',
    type: 'okr',
    title: 'Reduce Support Response Time',
    description: 'Decrease average support response time to improve customer experience.',
    owner: 'user-2',
    contributors: ['user-3'],
    status: 'at-risk',
    progress: 45,
    keyResults: [
      {
        id: 'kr-002-1',
        title: 'Reduce response time from 24h to 4h for urgent tickets',
        measurementType: 'number',
        startValue: 24,
        targetValue: 4,
        currentValue: 12,
        owner: 'user-2',
        weight: 60,
        confidenceLevel: 65,
        status: 'at-risk',
        lastUpdated: '2025-01-14T10:00:00Z',
        progressHistory: [],
      },
      {
        id: 'kr-002-2',
        title: 'Achieve 90% first contact resolution rate',
        measurementType: 'percentage',
        startValue: 72,
        targetValue: 90,
        currentValue: 75,
        owner: 'user-3',
        weight: 40,
        confidenceLevel: 60,
        status: 'at-risk',
        lastUpdated: '2025-01-12T10:00:00Z',
        progressHistory: [],
      },
    ],
    startDate: '2024-10-01',
    targetDate: '2025-03-31',
    timePeriod: 'Q4 2024 - Q1 2025',
    organization: 'department',
    department: 'Customer Support',
    parentGoalId: 'GOAL-001',
    childGoalIds: [],
    updateFrequency: 'weekly',
    autoCalculateFromKPIs: false,
    linkedFeatureIds: [],
    linkedSprintIds: ['SPRINT-001'],
    linkedInitiativeIds: [],
    tags: ['support', 'efficiency'],
    priority: 'high',
    visibility: 'team',
    createdAt: '2024-10-01T00:00:00Z',
    updatedAt: '2025-01-14T10:00:00Z',
    updates: [],
    comments: [],
  },
  {
    id: 'GOAL-003',
    type: 'kpi',
    title: 'Monthly Active Users (MAU)',
    description: 'Track and grow monthly active user count.',
    owner: 'user-1',
    contributors: [],
    status: 'on-track',
    progress: 68,
    startDate: '2024-10-01',
    targetDate: '2025-12-31',
    timePeriod: 'Annual 2025',
    organization: 'company',
    childGoalIds: [],
    updateFrequency: 'daily',
    autoCalculateFromKPIs: true,
    linkedFeatureIds: ['FEAT-003'],
    linkedSprintIds: [],
    linkedInitiativeIds: [],
    tags: ['growth', 'users'],
    priority: 'high',
    visibility: 'public',
    createdAt: '2024-10-01T00:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    updates: [],
    comments: [],
  },
  {
    id: 'GOAL-004',
    type: 'milestone',
    title: 'Launch API Version 2.0',
    description: 'Complete development and launch of API v2 with new features.',
    owner: 'user-3',
    contributors: ['user-1', 'user-2'],
    status: 'off-track',
    progress: 35,
    startDate: '2024-12-01',
    targetDate: '2025-06-30',
    timePeriod: 'H1 2025',
    organization: 'team',
    team: 'Engineering',
    childGoalIds: [],
    updateFrequency: 'weekly',
    autoCalculateFromKPIs: false,
    linkedFeatureIds: ['FEAT-004', 'FEAT-005'],
    linkedSprintIds: ['SPRINT-002'],
    linkedInitiativeIds: [],
    tags: ['api', 'product', 'engineering'],
    priority: 'critical',
    visibility: 'public',
    createdAt: '2024-12-01T00:00:00Z',
    updatedAt: '2025-01-10T10:00:00Z',
    updates: [],
    comments: [],
  },
];
